#!/usr/bin/env python3
"""Generate include/hermes_terminal/cyrillic_font.h from the glyph art below.

The stock 6x8 terminal font has ASCII glyphs only. This 5x7 set covers
U+0410..U+044F plus Ё/ё and is drawn by the firmware's own mini renderer at
the same 6 px advance, so Cyrillic text lines up with ASCII in every row.
Edit the art, re-run the script, rebuild.
"""
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "include" / "hermes_terminal" / "cyrillic_font.h"

# Order: А..Я (32), а..я (32), Ё, ё. Rows top to bottom, '#' = pixel on.
GLYPHS = """
А .###. #...# #...# ##### #...# #...# #...#
Б ##### #.... #.... ####. #...# #...# ####.
В ####. #...# #...# ####. #...# #...# ####.
Г ##### #.... #.... #.... #.... #.... #....
Д .#### .#..# .#..# .#..# .#..# ##### #...#
Е ##### #.... #.... ####. #.... #.... #####
Ж #.#.# #.#.# .###. ..#.. .###. #.#.# #.#.#
З .###. #...# ....# ..##. ....# #...# .###.
И #...# #...# #..## #.#.# ##..# #...# #...#
Й .#.#. ..#.. #...# #..## #.#.# ##..# #...#
К #...# #..#. #.#.. ##... #.#.. #..#. #...#
Л .#### .#..# .#..# .#..# .#..# .#..# #...#
М #...# ##.## #.#.# #.#.# #...# #...# #...#
Н #...# #...# #...# ##### #...# #...# #...#
О .###. #...# #...# #...# #...# #...# .###.
П ##### #...# #...# #...# #...# #...# #...#
Р ####. #...# #...# ####. #.... #.... #....
С .###. #...# #.... #.... #.... #...# .###.
Т ##### ..#.. ..#.. ..#.. ..#.. ..#.. ..#..
У #...# #...# #...# .#### ....# #...# .###.
Ф ..#.. .###. #.#.# #.#.# #.#.# .###. ..#..
Х #...# #...# .#.#. ..#.. .#.#. #...# #...#
Ц #..#. #..#. #..#. #..#. #..#. ##### ....#
Ч #...# #...# #...# .#### ....# ....# ....#
Ш #.#.# #.#.# #.#.# #.#.# #.#.# #.#.# #####
Щ #.#.# #.#.# #.#.# #.#.# #.#.# ##### ....#
Ъ ##... .#... .#... .###. .#..# .#..# .###.
Ы #...# #...# #...# ##..# #.#.# #.#.# ##..#
Ь #.... #.... #.... ####. #...# #...# ####.
Э .###. #...# ....# ..### ....# #...# .###.
Ю #..#. #.#.# #.#.# ###.# #.#.# #.#.# #..#.
Я .#### #...# #...# .#### ..#.# .#..# #...#
а ..... ..... .###. ....# .#### #...# .####
б ..### .#... #.... ####. #...# #...# .###.
в ..... ..... ####. #...# ####. #...# ####.
г ..... ..... ##### #.... #.... #.... #....
д ..... ..... .#### .#..# .#..# ##### #...#
е ..... ..... .###. #...# ##### #.... .###.
ж ..... ..... #.#.# .###. ..#.. .###. #.#.#
з ..... ..... ####. ....# .###. ....# ####.
и ..... ..... #...# #..## #.#.# ##..# #...#
й .#.#. ..#.. #...# #..## #.#.# ##..# #...#
к ..... ..... #..#. #.#.. ##... #.#.. #..#.
л ..... ..... .#### .#..# .#..# .#..# #...#
м ..... ..... #...# ##.## #.#.# #...# #...#
н ..... ..... #...# #...# ##### #...# #...#
о ..... ..... .###. #...# #...# #...# .###.
п ..... ..... ##### #...# #...# #...# #...#
р ..... ..... ####. #...# ####. #.... #....
с ..... ..... .###. #.... #.... #.... .###.
т ..... ..... ##### ..#.. ..#.. ..#.. ..#..
у ..... ..... #...# #...# .#### ....# .###.
ф ..#.. .###. #.#.# #.#.# .###. ..#.. ..#..
х ..... ..... #...# .#.#. ..#.. .#.#. #...#
ц ..... ..... #..#. #..#. #..#. ##### ....#
ч ..... ..... #...# #...# .#### ....# ....#
ш ..... ..... #.#.# #.#.# #.#.# #.#.# #####
щ ..... ..... #.#.# #.#.# #.#.# ##### ....#
ъ ..... ..... ##... .#... .###. .#..# .###.
ы ..... ..... #...# #...# ##..# #.#.# ##..#
ь ..... ..... #.... #.... ####. #...# ####.
э ..... ..... ####. ....# .#### ....# ####.
ю ..... ..... #.##. #.#.# ###.# #.#.# #.##.
я ..... ..... .#### #...# .#### .#..# #...#
Ё .#.#. ##### #.... ####. #.... #.... #####
ё .#.#. ..... .###. #...# ##### #.... .###.
"""

EXPECTED = [chr(c) for c in range(0x410, 0x450)] + ["Ё", "ё"]


def main() -> int:
    rows = [line.split() for line in GLYPHS.strip().splitlines()]
    letters = [row[0] for row in rows]
    if letters != EXPECTED:
        raise SystemExit(f"glyph order mismatch: {letters}")
    lines = []
    for row in rows:
        letter, *art = row
        if len(art) != 7 or any(len(r) != 5 for r in art):
            raise SystemExit(f"bad art for {letter}")
        packed = ", ".join(
            "0x%02X" % int("".join("1" if c == "#" else "0" for c in r), 2)
            for r in art)
        lines.append(f"    {{{packed}}},  // {letter} U+{ord(letter):04X}")
    OUTPUT.write_text(
        "#pragma once\n\n#include <cstdint>\n\n"
        "// 5x7 Cyrillic glyphs for the 6x8 terminal font cell. Rows top to\n"
        "// bottom, bit 4 is the leftmost column. Index 0..63 = U+0410..U+044F,\n"
        "// 64 = Ё (U+0401), 65 = ё (U+0451).\n"
        "// Generated by scripts/generate_cyrillic_font.py; do not edit.\n"
        "namespace hermes_terminal {\n\n"
        "constexpr int kCyrillicGlyphCount = 66;\n"
        "const std::uint8_t kCyrillicGlyphs[kCyrillicGlyphCount][7] = {\n"
        + "\n".join(lines) + "\n};\n\n"
        "// Returns the glyph row index for a code point, or -1 if not covered.\n"
        "inline int cyrillicGlyphIndex(std::uint32_t codePoint)\n{\n"
        "    if (codePoint >= 0x0410 && codePoint <= 0x044F) return static_cast<int>(codePoint - 0x0410);\n"
        "    if (codePoint == 0x0401) return 64;\n"
        "    if (codePoint == 0x0451) return 65;\n"
        "    return -1;\n}\n\n"
        "}  // namespace hermes_terminal\n",
        encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)} with {len(rows)} glyphs")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
