#!/usr/bin/env python3
"""Generate the packed 2-bit Hermes portrait headers (READY, blink, WORK).

Usage: python3 scripts/generate_hermes_portraits.py

Pipeline per frame: crop the artwork's own frame line, resize to 88x88,
flood-fill the paper connected to the border to the transparent index, and
quantize the rest with a 4x4 Bayer halftone into black / muted / ink. The
blink frame reuses the READY bytes outside the eye box so the two frames
never drift apart. Requires Pillow only.
"""
from __future__ import annotations

from pathlib import Path

import numpy as np
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / "docs" / "assets"
INCLUDE = ROOT / "include" / "hermes_terminal"
WIDTH = HEIGHT = 92
SIZE = 88
OFFSET = (WIDTH - SIZE) // 2
PAPER_THRESHOLD = 190
EYE_BOX = (26, 35, 46, 51)  # x0, y0, x1, y1 in packed 92x92 coordinates

BAYER4 = (np.array([[0, 8, 2, 10], [12, 4, 14, 6], [3, 11, 1, 9], [15, 7, 13, 5]]) + 0.5) / 16.0


def crop_frame(image: Image.Image) -> Image.Image:
    grey = np.array(image)
    frame = -1
    for y in range(min(20, grey.shape[0])):
        if (grey[y] < 100).mean() > 0.5:
            frame = y
    crop = frame + 3 if frame >= 0 else 0
    return image.crop((crop, crop, image.width - crop, image.height - crop))


def background_mask(grey: np.ndarray) -> np.ndarray:
    height, width = grey.shape
    mask = np.zeros((height, width), bool)
    light = grey >= PAPER_THRESHOLD
    stack = [(y, x) for y in range(height) for x in (0, width - 1)]
    stack += [(y, x) for x in range(width) for y in (0, height - 1)]
    while stack:
        y, x = stack.pop()
        if y < 0 or x < 0 or y >= height or x >= width:
            continue
        if mask[y, x] or not light[y, x]:
            continue
        mask[y, x] = True
        stack += [(y + 1, x), (y - 1, x), (y, x + 1), (y, x - 1)]
    return mask


def levels_for(path: Path) -> np.ndarray:
    image = crop_frame(Image.open(path).convert("L"))
    grey = np.array(image.resize((SIZE, SIZE), Image.LANCZOS)).astype(float)
    mask = background_mask(grey)
    value = grey / 255.0
    frame = np.zeros((HEIGHT, WIDTH), int)
    for y in range(SIZE):
        for x in range(SIZE):
            if mask[y, x]:
                continue
            scaled = value[y, x] * 2.0
            base = int(scaled)
            level = base + (1 if scaled - base > BAYER4[y % 4, x % 4] else 0)
            frame[OFFSET + y, OFFSET + x] = 1 + min(level, 2)
    return frame


def pack(frame: np.ndarray) -> bytes:
    flat = frame.reshape(-1)
    return bytes((int(flat[i]) << 6) | (int(flat[i + 1]) << 4) |
                 (int(flat[i + 2]) << 2) | int(flat[i + 3])
                 for i in range(0, flat.size, 4))


def array(name: str, encoded: bytes) -> str:
    rows = []
    for offset in range(0, len(encoded), 16):
        rows.append("    " + ", ".join(f"0x{v:02X}" for v in encoded[offset:offset + 16]) + ",")
    return f"const std::uint8_t {name}[] = {{\n" + "\n".join(rows) + "\n};\n"


def main() -> int:
    ready = levels_for(ASSETS / "hermes-ready.png")
    blink_source = levels_for(ASSETS / "hermes-blink.png")
    working = levels_for(ASSETS / "hermes-working.png")
    blink = ready.copy()
    x0, y0, x1, y1 = EYE_BOX
    blink[y0:y1, x0:x1] = blink_source[y0:y1, x0:x1]

    (INCLUDE / "hermes_badge.h").write_text(
        "#pragma once\n\n#include <cstddef>\n#include <cstdint>\n\n"
        "// Official Hermes portrait, 4x4 Bayer halftone in the Pocket Terminal\n"
        "// palette. Four pixels per byte (MSB first): transparent background,\n"
        "// black, muted grey, or warm ink. The paper around the figure is\n"
        "// transparent so the portrait sits directly on the graphite panel.\n"
        "// Generated by scripts/generate_hermes_portraits.py; do not edit.\n"
        f"constexpr int kHermesBadgeWidth = {WIDTH};\n"
        f"constexpr int kHermesBadgeHeight = {HEIGHT};\n\n"
        + array("kHermesBadge2Bpp", pack(ready))
        + "\nstatic_assert(sizeof(kHermesBadge2Bpp) ==\n"
        "                  static_cast<std::size_t>(kHermesBadgeWidth) *\n"
        "                      kHermesBadgeHeight / 4,\n"
        "              \"Hermes badge must be packed 2-bit 92x92\");\n",
        encoding="utf-8")
    (INCLUDE / "hermes_states.h").write_text(
        "#pragma once\n\n#include <cstdint>\n\n"
        "#include \"hermes_terminal/hermes_badge.h\"\n\n"
        "// Optional expressive states. The blink frame is pixel-identical to\n"
        "// the READY portrait outside the visible eye region.\n"
        "// Generated by scripts/generate_hermes_portraits.py; do not edit.\n"
        + array("kHermesWorking2Bpp", pack(working)) + "\n"
        + array("kHermesBlink2Bpp", pack(blink)),
        encoding="utf-8")
    changed = int((blink != ready).sum())
    print(f"wrote READY/blink/WORK frames; blink differs in {changed} pixels")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
